### ISSUE TITLE
GitHub and casl-dev repos are out of sync

### ISSUE THREAD

**Issue by dalg24** [CASL/vera_tpls#7]
Below is the diff between the oneline log of this repo versus the one hosted on casl-dev:
```
$ diff github casldev
1,5c1,2
< 70b9dde Adding to build NETCDF 4.4.1 in support of ticket #4239
< 58defd4 Merge pull request #6 from dalg24/hdf5_with_zlib
< 3a983ca Make HDF5 detect ZLIB in Docker build
< 4a1d862 Merge pull request #4 from dalg24/gcc5
< d55720e Merge pull request #1 from dalg24/fix_dependencies
---
> 945950e Updating to build NETCDF 4.4.1 in support of ticket #4239
> 24b7f18 Patched HDF5 1.8.10 for use with GCC-4.9.3, corrected C++ comments.
8,10d4
< d3a898c Patch boost-1.50.0 to compile with gcc-5
< eaa9961 Patch hdf5-1.8.10 source to compile with gcc-5
< 3304c5a Register dependencies for SLEPC
```

**Comment by dalg24** [comment]
Let me elaborate on this.  It means the version that has been tagged `vera-tpls-2.6` does **not** have the changes that are **required** to build the Docker base image that has the VERA Dev Env and the TPLs.

**Comment by dalg24** [comment]
@bartlettroscoe @turner61 who administrates the CASL organization on GitHub?  Would you add me to it?

**Comment by bartlettroscoe** [comment]
@dalg24, tried to add you as a "Collaborator" with "write" access.  Now, if you have write access to the casl-dev vera_tpls repo,then you can fix this.  If you need to do any `git push -f` commands, let me know and I can open that up (temporarily).

**Comment by dalg24** [comment]
I deleted the old "vera-tpls-2.6" and recreated it after the merge of #5.
We forced push to casl-dev so this is resolved now.
